import 'package:project_intern/presenter/model/chatmodel.dart';

List<ChatModel> chats = [
  ChatModel(content: 'Xin chào', type: 'sender'),
  ChatModel(content: 'Chào bạn', type: 'receiver'),
  ChatModel(content: 'Bạn tên gì ?', type: 'sender'),
  ChatModel(content: 'Tôi tên Hiếu, còn bạn', type: 'receiver'),
  ChatModel(content: 'Oh, tôi tên Quân', type: 'sender'),
  ChatModel(content: 'Vậy à, làm bạn của nhau nhé Quân !', type: 'receiver'),
  ChatModel(content: 'OK Hiếu nha, best friend !', type: 'sender'),
  ChatModel(content: 'Oke Quân', type: 'receiver'),
  ChatModel(content: 'Nhà bạn ở đâu', type: 'sender'),
  ChatModel(content: 'Nhà tôi ở Hà Nội, còn bạn', type: 'receiver'),
  ChatModel(content: 'Nhà tôi ở TP HCM', type: 'sender'),
  ChatModel(content: 'Vậy à, làm bạn của nhau nhé Quân !', type: 'receiver'),
  ChatModel(content: 'OK Hiếu nha, best friend !', type: 'sender'),
  ChatModel(content: 'Oke Quân', type: 'receiver'),
  ChatModel(content: 'Nhà bạn ở đâu', type: 'sender'),
  ChatModel(content: 'Nhà tôi ở Hà Nội, còn bạn', type: 'receiver'),
  ChatModel(content: 'Nhà tôi ở TP HCM', type: 'sender'),
  ChatModel(content: 'Vậy à, làm bạn của nhau nhé Quân !', type: 'receiver'),
  ChatModel(content: 'OK Hiếu nha, best friend !', type: 'sender'),
  ChatModel(content: 'Oke Quân', type: 'receiver'),
  ChatModel(content: 'Nhà bạn ở đâu', type: 'sender'),
  ChatModel(content: 'Nhà tôi ở Hà Nội, còn bạn', type: 'receiver'),
  ChatModel(content: 'Nhà tôi ở TP HCM', type: 'sender'),
  ChatModel(content: 'Vậy à, làm bạn của nhau nhé Quân !', type: 'receiver'),
  ChatModel(content: 'OK Hiếu nha, best friend !', type: 'sender'),
  ChatModel(content: 'Oke Quân', type: 'receiver'),
  ChatModel(content: 'Nhà bạn ở đâu', type: 'sender'),
  ChatModel(content: 'Nhà tôi ở Hà Nội, còn bạn', type: 'receiver'),
  ChatModel(content: 'Nhà tôi ở TP HCM', type: 'sender'),
];
